//------------------------------------------------------------------------------
// <auto-generated>
//    Bu kod bir şablondan oluşturuldu.
//
//    Bu dosyada el ile yapılan değişiklikler uygulamanızda beklenmedik davranışa neden olabilir.
//    Kod yeniden oluşturulursa, bu dosyada el ile yapılan değişikliklerin üzerine yazılacak.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospital_UI
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PersonelEntities : DbContext
    {
        public PersonelEntities()
            : base("name=PersonelEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Asistan> Asistans { get; set; }
        public DbSet<Cleaning_Staff> Cleaning_Staff { get; set; }
        public DbSet<Departmant> Departmants { get; set; }
        public DbSet<Doctor> Doctors { get; set; }
        public DbSet<Login> Logins { get; set; }
        public DbSet<Nurse> Nurses { get; set; }
        public DbSet<Salary> Salaries { get; set; }
        public DbSet<Shift> Shifts { get; set; }
    }
}
