//------------------------------------------------------------------------------
// <auto-generated>
//    Bu kod bir şablondan oluşturuldu.
//
//    Bu dosyada el ile yapılan değişiklikler uygulamanızda beklenmedik davranışa neden olabilir.
//    Kod yeniden oluşturulursa, bu dosyada el ile yapılan değişikliklerin üzerine yazılacak.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospital_UI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nurse
    {
        public int id { get; set; }
        public string name { get; set; }
        public string surname { get; set; }
        public System.DateTime age { get; set; }
        public int salary_id { get; set; }
        public bool isSentry { get; set; }
    }
}
